root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./app"
  bin = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]

[log]
  time = true

[misc]
  clean_on_exit = true